score_job:
  cron: "1 * * * * Asia/Seoul"
  class: "ScoreJob"
  queue: default
summary_mailing_job:
  class: IssuesSummaryMailingJob
  cron: "*/25 * * * 1 Asia/Seoul"
  queue: default
clypit_job:
  class: ClypitJob
  cron: "*/5 * * * * Asia/Seoul"
  queue: default
comment_order_job:
  class: CommentOrderJob
  cron: "*/5 * * * * Asia/Seoul"
  queue: default
